// ==UserScript==
// @name         FeedSieve → X Muted Words Manager (中文词库)
// @namespace    feedsieve-x-muted-zh
// @version      4.1.4
// @description  中文 X 隐藏词油猴脚本：内置词库、去重、15条分批、暂停/继续、自定义秒数、关键词管理
// @match        https://x.com/*
// @match        https://www.x.com/*
// @match        https://twitter.com/*
// @match        https://www.twitter.com/*
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_registerMenuCommand
// @grant        GM.registerMenuCommand
// @run-at       document-start
// @homepageURL  https://github.com/uumego/feedsieve-x-muted-words
// @supportURL   https://github.com/uumego/feedsieve-x-muted-words/issues
// ==/UserScript==
(()=>{'use strict';
function regMenu(name,fn){try{if(typeof GM_registerMenuCommand==='function')return GM_registerMenuCommand(name,fn);if(typeof GM!=='undefined'&&typeof GM.registerMenuCommand==='function')return GM.registerMenuCommand(name,fn)}catch(e){console.warn('[FSX] menu registration failed',e)}}
function goMuted(){location.href='https://x.com/settings/muted_keywords'}
regMenu('FSX：打开 X 已隐藏字词页面',goMuted);
regMenu('FSX：显示 / 恢复控制面板',()=>istarget()?panel():goMuted());
regMenu('FSX：暂停自动添加',()=>pause());
regMenu('FSX：管理关键词',()=>istarget()?manager():goMuted());
function launcher(){if(!document.body||document.getElementById('fsxz-launcher'))return;let b=document.createElement('button');b.id='fsxz-launcher';b.textContent='FSX';b.title='FeedSieve → X 关键词管理';b.style='position:fixed;right:18px;bottom:18px;z-index:2147483647;background:#1d9bf0;color:#fff;border:0;border-radius:999px;width:48px;height:48px;font:bold 13px Arial;box-shadow:0 4px 18px #0006;cursor:pointer';b.onclick=()=>istarget()?panel():goMuted();document.body.appendChild(b)}
document.addEventListener('DOMContentLoaded',launcher,{once:true});
setInterval(launcher,700);
const V='4.1.4',S='2026.09.13.2-zh',P='fsxz',T={"ready":"准备就绪","scan":"正在扫描 X 已隐藏词…","active":"当前启用","batch":"每批","next":"下一批间隔","sec":"秒","min":"最少","start":"开始 / 继续","running":"自动运行中","pause":"暂停","once":"只运行一批（15条）","manage":"管理关键词","scanbtn":"扫描全部已添加","local":"查看本地进度","mgr":"关键词管理","search":"搜索关键词","customph":"添加自定义关键词：一行一个，也支持逗号分隔","add":"添加","export":"导出启用词","reset":"恢复内置默认状态","close":"关闭","defaulton":"内置·默认开","defaultoff":"内置·默认关","custom":"自定义","enable":"启用","disable":"停用","delete":"删除","paused":"已暂停，进度已保存","all":"全部关键词已经处理完成","failpause":"连续失败，已自动暂停","added":"已添加自定义关键词","resetq":"恢复所有内置关键词默认状态？自定义关键词不会删除。"},W=`18禁
99bb
AV女优
AV男优
SM全明星
SM舞会
SM虐恋
SM调教
a4y
adult
a片
gay片
g点
g片
h动漫
h动画
incest
secom
sexinsex
sm女王
tokyohot
xiao77
xing伴侣
xxoo
yin荡
一ye情
一丝不挂
一夜情
一夜欢
一本道
三级
三级片
三陪
上门约炮
下体
不穿
专业牵线
丝袜
丝诱
两性知识
中年美妇
主页自取福利
主页领取福利
买春
乱交
乱伦
乱伦小
乱伦类
乱奸
乳交
乳头
乳房
乳晕
乳沟
乳爆
乳神
亚情
人体摄影
人兽
人妻
人妻熟女
仓井空
伦图
伦理
伦理大
伦理毛
伦理片
伦理电影
体位
体奸
做爱
偷拍
偷欢
偷窥
免费A片
全国1-5线覆盖
全国空降
全裸
兽交
兽奸
兽性
兽欲
内射
写真
凌辱
几吧
出轨
前凸后翘
包二奶
卖淫
厕奴
原味内衣
双乳
双峰
双性恋
双臀
发情
发浪
发生关系
口交
口射
口活
口淫
口爆
叫床
吃精
各种姿势
同城上门约炮
同城可约
同城私约
同城空降
同城约炮
同房
后庭
后穴
吞精
呻吟
品香堂
喷精
四房色播
国产av
处女
处男
夏川纯
多人轮
多人运动
夜勤病栋
大乳
大力抽送
大波
奈美
套弄
女优
奶子
奸情
好嫩
妓女
妹上门
妹按摩
婬
嫖娼
嫖客
嫩B
嫩女
嫩穴
嫩逼
学生妹
学生妹上门
寂寞女
寂寞少妇
寂寞男
密穴
封面女郎
射爽
射精
射颜
小xue
小穴
小逼
少修正
少妇
少妇上门
少妇自慰
少年阿宾
少男少女
就去日
屁眼
屄
巨乳
巨奶
巨屌
干死你
干穴
幼b
幼交
幼女
幼师
幼男
幼逼
幼齿
应召
开苞
张筱雨
强jian
强奸
强奸处女
强暴
快感
性交
性交图片
性交易
性交视频
性伙伴
性伴侣
性器
性器官
性奴
性奴集中营
性息
性感
性感妖娆
性感少
性感沙滩
性感诱惑
性技巧
性服务
性欲
性爱
性爱动态图
性爱动漫
性爱图
性爱图片
性爱姿势
性爱小电影
性爱插图
性爱电影
性爱视
性爱贴图
性生活
性瘾
性福情
性虎
性虐
性虐待
性行为
性饥渴
性高潮
情欲
情色
情色图片
情色小说
情色成人
情色电影
情色视频
情趣内衣
情趣用品
惹火身材
成人dv
成人卡通
成人图
成人小
成人小说
成人文
成人文学
成人杂志
成人游戏
成人漫画
成人片
成人用品
成人电
成人电影
成人网站
成人聊
成人色情
成人视
成人论坛
成年片
我就色
我干
我福不黑
手淫
扌由插
抓胸
抽一插
抽插
拉拉香港
拔出来
招妓
招鸡
拳交
按摩棒
捏弄
换妻
换妻俱乐部
换媳
揉乳
插b
插我
插暴
插比
插进
插逼
插阴
援交
援助交际
摸奶
摸奶门
摸胸
操我
操死
操烂
操逼
操黑
放尿
文学情色
无修正
无偿约
无码
无码AV
日本AV
日本AV女优
日本SM调教
日本拉拉
日本淫电影
日本淫荡美少女
日烂
日逼
春宫
春药
暴乳
暴奸
暴干
暴淫
有码
未满
杨思敏
松岛枫
校鸡
梦幻西游性爱版
欧美BT
欲仙欲死
欲女
欲火
死逼
母奸
汤加丽
流出
流淫
浑圆
浪叫
浪女
浪妇
浪逼
淫书
淫乱
淫乱熟女
淫乳
淫亵
淫兽
淫兽学
淫兽学园
淫叫
淫声
淫声浪语
淫女
淫妇
淫妻
淫姐
淫威
淫娃
淫媚
淫情
淫情女
淫教师
淫术炼金士
淫样
淫母
淫水
淫河
淫流
淫浪
淫液
淫照
淫电影
淫秽
淫穴
淫糜
淫肉
淫色
淫荡
淫荡照片
淫荡笑话
淫荡美女
淫荡视频
淫蕩
淫虐
淫虫
淫虫电影
淫贱
淫赶
淫靡
淫騷妹
淫魔
淫魔舞
深喉
滥交
漏乳
潮吹
潮喷
激情打炮
火辣
炮友
点击头像看福利
熟女
熟妇
熟母
爆乳
爆草
爱女人
爱情岛论坛
爱液
爱爱
爱爱视频
爽死我了
爽片
狂插
狂操
狼友
猛男
猥亵
玉乳
玉女心经
玉穴
玉蒲团
现代情色
生殖器
电影色情
男公关
男女公关
男奴
白嫩
盗撮
相奸
真人上门
砲友
破处
禁室培欲
福利合集在主页
福利在主页
福利在简介
福利视频在主页
福利视频在简介
福利链接在主页
福利链接在简介
私信发福利视频
私信看福利视频
秘唇
穴口
穴图
空姐
粉嫩
粉穴
精子
精液
素人
素质男
约炮
线下私约
绿帽
美乳
美女上门
美女写真
美女图片
美女斗地主
美女裸体
美女裸聊
美少妇
美幼
美穴
美腿
美艳少妇
美逼
羞羞
群交
聊性
肉体
肉具
肉唇
肉弹
肉棍
肉棒
肉欲
肉洞
肉穴
肉缝
肉茎
肉逼
肏你
肏死
肛交
肛洞
肛门
肛门喷水
肥逼
背德
胸推
胸部
脚交
脱光
脱内裤
脱衣
脱裤
腋毛女
自慰
自拍
舔脚
舔阴
舞女
色b
色区
色即是空
色妹妹
色小说
色情图片
色情小说
色情影片
色情服务
色情片
色情电影
色情网站
色情表演
色欲
色狼
色猫
色电影
色界
色盟
色色
色视频
色诱
色逼
艳情小说
艳照
艳舞女郎
花花公子
荡女
荡妇
菊穴
菊花洞
菊门
蜜液
蜜穴
被干
被插
被操
裙中性运动
裤袜
裸体
裸体写真
裸体照片
裸照
裸聊
裸聊网
裸聊视频
裸舞视
裸陪
裸露
裹本
要射了
视频合集在主页
视频美女
视频聊天
诱奸
诱惑
豪乳
赤裸
轮奸
轮操
轮暴
进主页看福利
迷奸
逼奸
酒瓶插入
酥痒
释欲
金鳞岂是池中物
金麟岂是池中物
铃木麻
阉割
阳具
阴b
阴唇
阴囊
阴户
阴核
阴毛
阴精
阴茎
阴茎助勃
阴茎勃起
阴茎增大
阴蒂
阴道
阴道口
阴部
阴阜
阿姨
附近可约
陰唇
陰戶
陰核
陰道
集体淫
露b
颜射
风月大陆
风骚
食精
骚嘴
骚女
骚妇
骚比
骚水
骚浪
骚穴
骚货
骚逼
高清性愛
高潮
鬼畜抄
魅惑
鸡吧
鸡奸
鸡巴
黄片
黄色网站
黑逼
龟头
没人比她骚
没人比我骚
主页能打
usdt giveaway
usdc giveaway
btc giveaway
eth giveaway
sol giveaway
trx giveaway
tron giveaway
crypto giveaway
bitcoin giveaway
giweaway
giv3away
claim on tron
claim on tron network
instant claim on tron
claim your share now
times ticking
act fast
500 usdt
follow to claim
airdrop claim now
free crypto now
no kyc
win usdt
dm to claim
repost to claim`.split('\n').filter(Boolean),D=new Set(`adult
三级
不穿
专业牵线
丝袜
写真
出轨
双峰
发生关系
各种姿势
同房
处女
处男
多人运动
大波
奈美
好嫩
学生妹
少妇
少男少女
幼师
快感
性感
性感妖娆
性感少
性感沙滩
性感诱惑
情欲
我干
拔出来
捏弄
无码
有码
未满
流出
浑圆
火辣
熟女
爱女人
猛男
白嫩
封面女郎
花花公子
背德
脱光
脱衣
脱裤
自拍
舞女
色即是空
色狼
裤袜
裸体
裸露
视频美女
视频聊天
诱惑
酥痒
阉割
阿姨
风骚
高潮
魅惑
空姐
素人
绿帽
美女写真
美女图片
美腿
肉体
下体
两性知识
乳头
乳房
乳晕
乳沟
人体摄影
体位
双性恋
性交
性伙伴
性伴侣
性器
性器官
性技巧
性欲
性生活
性瘾
性行为
性高潮
情趣内衣
情趣用品
成人用品
按摩棒
手淫
自慰
生殖器
胸部
精子
精液
肛门
阴唇
阴囊
阴户
阴核
阴毛
阴茎
阴蒂
阴道
阴道口
阴部
阴阜
陰唇
陰戶
陰核
陰道
偷拍
偷窥
凌辱
卖淫
嫖娼
援交
强奸
强暴
性交易
性虐待
猥亵
人妻
伦理
男公关
男女公关
times ticking
act fast
500 usdt
no kyc`.split('\n').map(n));
const C={B:15,d1:3500,d2:5500,def:300,min:60,max:86400,wait:1300,tries:2,rounds:220,scanwait:700,nonew:10},K=x=>P+'_'+x;
let busy=false,loop=null;const sl=m=>new Promise(r=>setTimeout(r,m)),cl=s=>String(s||'').normalize('NFKC').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\u00A0/g,' ').replace(/\s+/g,' ').trim(),n=s=>cl(s).toLowerCase(),uniq=a=>[...new Map((a||[]).map(x=>[n(x),cl(x)]).filter(x=>x[0])).values()];
const gs=(k,d)=>GM_getValue(K(k),d),ss=(k,v)=>GM_setValue(K(k),v),del=k=>GM_deleteValue(K(k)),sets=k=>new Set((gs(k,[])||[]).map(n));
function keys(s){let o=String(s||'').normalize('NFKC').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\u00A0/g,' ').trim(),z=new Set([n(o)]),a=o.split(/\s{2,}/)[0],b=o.split(/[｜|—–：:]+/)[0];if(a)z.add(n(a));if(b)z.add(n(b));return[...z].filter(Boolean)}
function interval(v){v=parseInt(v,10);return Number.isFinite(v)?Math.max(C.min,Math.min(C.max,v)):C.def}function geti(){let v=interval(gs('int',C.def));ss('int',v);return v}function seti(v){v=interval(v);ss('int',v);if(gs('auto',false)&&gs('next',0)>Date.now())ss('next',Date.now()+v*1000);draw();return v}
function state(w){let k=n(w),off=sets('off'),on=sets('on');return D.has(k)?on.has(k):!off.has(k)}function toggle(w,on){let k=n(w),a=sets('off'),b=sets('on');if(D.has(k)){on?b.add(k):b.delete(k);a.delete(k)}else{on?a.delete(k):a.add(k);b.delete(k)}ss('off',[...a]);ss('on',[...b])}
function custom(){return uniq(gs('custom',[]))}function active(){let m=new Map;for(let w of W)if(state(w))m.set(n(w),w);for(let w of custom())m.set(n(w),w);return[...m.values()]}function success(){return uniq(gs('ok',[]))}function saveok(a){ss('ok',uniq(a))}
function btn(re){return[...document.querySelectorAll('button,[role="button"],a')].find(e=>re.test(cl(e.innerText||e.textContent||e.getAttribute('aria-label'))))}function setv(e,v){let p=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,s=Object.getOwnPropertyDescriptor(p,'value')?.set;s?s.call(e,v):e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))}
function visible(){let m=new Map,x=document.querySelector('main');if(!x)return m;for(let d of x.querySelectorAll('div')){let l=String(d.innerText||'').split('\n').map(cl).filter(Boolean);if(l.length===2&&/^(永久|forever)$/i.test(l[1])&&l[0].length<=120)m.set(n(l[0]),l[0])}return m}
async function scan(cb){if(location.pathname.includes('/settings/add_muted_keyword')){history.back();await sl(1800)}await sl(1100);let m=new Map,last=0,no=0;scrollTo(0,0);await sl(700);for(let i=0;i<C.rounds;i++){for(let [k,v]of visible())m.set(k,v);no=m.size===last?no+1:0;last=m.size;cb?.(`${T.scan}\n${m.size}`);if(no>=C.nonew)break;let b=scrollY;scrollBy(0,Math.max(650,innerHeight*.8));await sl(C.scanwait);if(Math.abs(scrollY-b)<3)no++}return m}
async function addpage(){if(location.pathname.includes('/settings/add_muted_keyword'))return;let a=document.querySelector('a[href="/settings/add_muted_keyword"]')||btn(/^(添加|新增|add|\+)$/i);if(!a)throw Error('Add button not found');a.click();await sl(C.wait)}function input(){return document.querySelector('input[name="keyword"]')||[...document.querySelectorAll('input,textarea')].find(e=>/word|phrase|keyword|字词|关键词/i.test((e.placeholder||'')+' '+(e.getAttribute('aria-label')||'')))}
async function one(w){await addpage();let i=input();if(!i)throw Error('Keyword input not found');i.focus();setv(i,w);await sl(400);let s=btn(/^(保存|save)$/i);if(!s||s.disabled||s.getAttribute('aria-disabled')==='true')throw Error('Save button unavailable');s.click();await sl(1500);if(/出了点问题|稍后再试|try again|something went wrong|rate limit|too many/i.test(document.body.innerText||''))throw Error('X may be rate-limiting changes')}
function status(s){let e=document.getElementById(P+'-status');if(e)e.innerText=s;console.log('[FSX]',s)}function already(x){let s=new Set;for(let w of x.values())for(let k of keys(w))s.add(k);for(let w of success())for(let k of keys(w))s.add(k);return s}
async function batch(auto=false){if(busy)return{busy:true};busy=true;draw();try{status(T.scan+'\n'+T.active+': '+active().length);let x=await scan(status),a=already(x),p=active().filter(w=>!keys(w).some(k=>a.has(k)));if(!p.length){status(T.all);return{done:true}}let q=p.slice(0,C.B),f=0,ok=0,errs=gs('bad',[]);for(let j=0;j<q.length;j++){if(auto&&!gs('auto',false))return{pause:true};let w=q[j];status(`${j+1}/${q.length} · ${w}`);try{await one(w);ok++;f=0;for(let k of keys(w))a.add(k);saveok([...success(),w])}catch(e){f++;errs.push({word:w,error:e.message,time:new Date().toISOString()});ss('bad',errs);if(f>=C.tries){ss('auto',false);del('next');status(T.failpause+'\n'+e.message);return{stop:true}}}if(j<q.length-1)await sl(C.d1+Math.random()*(C.d2-C.d1))}return{done:p.length-ok<=0}}catch(e){status('Error: '+e.message);if(auto)ss('auto',false);return{stop:true}}finally{busy=false;draw()}}
async function autoloop(){while(gs('auto',false)){let r=await batch(true);if(r.done){ss('auto',false);del('next');status(T.all);break}if(r.stop||r.pause||!gs('auto',false))break;ss('next',Date.now()+geti()*1000);while(gs('auto',false)&&gs('next',0)>Date.now()){status(`${T.running}\n${Math.ceil((gs('next',0)-Date.now())/1000)} ${T.sec}`);await sl(1000)}del('next')}}
function start(){ss('auto',true);if(!loop)loop=autoloop().finally(()=>{loop=null;draw()});draw()}function pause(){ss('auto',false);del('next');status(T.paused);draw()}
const eh=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function manager(){if(!document.body)return;document.getElementById(P+'-mgr')?.remove();let o=document.createElement('div');o.id=P+'-mgr';o.style='position:fixed;inset:0;background:#000b;z-index:10000000;display:flex;align-items:center;justify-content:center';o.innerHTML=`<div style="width:min(820px,94vw);height:min(780px,90vh);background:#111;color:#fff;border-radius:16px;padding:16px;display:flex;flex-direction:column"><div style="display:flex;justify-content:space-between"><b>${T.mgr}</b><button id="${P}-close">${T.close}</button></div><input id="${P}-search" placeholder="${T.search}" style="margin:10px 0;padding:8px;background:#000;color:#fff;border:1px solid #444"><div style="display:flex;gap:8px"><textarea id="${P}-addtext" placeholder="${T.customph}" style="flex:1;height:65px;background:#000;color:#fff"></textarea><button id="${P}-add">${T.add}</button></div><div style="margin:8px 0"><button id="${P}-export">${T.export}</button> <button id="${P}-reset">${T.reset}</button></div><div id="${P}-stats" style="font-size:12px;color:#aaa"></div><div id="${P}-list" style="flex:1;overflow:auto"></div></div>`;document.body.appendChild(o);
function render(){let q=n(document.getElementById(P+'-search').value),rows=W.map(w=>({w,src:'b',on:state(w),d:D.has(n(w))})).concat(custom().map(w=>({w,src:'c',on:true,d:false}))).filter(r=>!q||n(r.w).includes(q));document.getElementById(P+'-stats').textContent=`${W.length} built-in · ${D.size} default off · ${custom().length} custom · ${active().length} active`;document.getElementById(P+'-list').innerHTML=rows.map(r=>`<div style="display:flex;padding:6px;border-bottom:1px solid #222;opacity:${r.on?1:.45}"><span style="flex:1">${eh(r.w)} <small>${r.src==='c'?T.custom:(r.d?T.defaultoff:T.defaulton)}</small></span><button data-w="${eh(r.w)}" data-s="${r.src}">${r.src==='c'?T.delete:(r.on?T.disable:T.enable)}</button></div>`).join('');document.querySelectorAll('#'+P+'-list button').forEach(b=>b.onclick=()=>{let w=b.dataset.w;if(b.dataset.s==='c')ss('custom',custom().filter(x=>n(x)!==n(w)));else toggle(w,!state(w));render();draw()})}
document.getElementById(P+'-close').onclick=()=>o.remove();document.getElementById(P+'-search').oninput=render;document.getElementById(P+'-add').onclick=()=>{let e=document.getElementById(P+'-addtext'),a=e.value.split(/[\n,，;；]+/).map(cl).filter(Boolean),b=custom();ss('custom',uniq([...b,...a]));e.value='';status(T.added);render();draw()};document.getElementById(P+'-export').onclick=()=>{let a=document.createElement('a'),u=URL.createObjectURL(new Blob([active().join('\n')],{type:'text/plain;charset=utf-8'}));a.href=u;a.download='x-muted-zh-'+S+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};document.getElementById(P+'-reset').onclick=()=>{if(confirm(T.resetq)){del('off');del('on');render();draw()}};render()}
function draw(){let e=document.getElementById(P+'-panel');if(!e)return;let a=gs('auto',false),s=document.getElementById(P+'-start'),p=document.getElementById(P+'-pause'),i=document.getElementById(P+'-int');s.textContent=a?T.running:T.start;s.disabled=a||busy;p.disabled=!a;if(i&&document.activeElement!==i)i.value=geti();document.getElementById(P+'-meta').textContent=`v${V} · ${T.active} ${active().length} · ${T.batch} ${C.B}`}
function panel(){if(!document.body||document.getElementById(P+'-panel'))return;let e=document.createElement('div');e.id=P+'-panel';e.style='position:fixed;right:22px;bottom:22px;width:340px;padding:15px;z-index:9999999;border-radius:16px;background:#111;color:#fff;font-family:Arial,sans-serif;box-shadow:0 8px 30px #0006';e.innerHTML=`<b>FeedSieve → X v${V}</b><div id="${P}-meta" style="font-size:11px;color:#888;margin:4px 0"></div><div id="${P}-status" style="white-space:pre-line;font-size:13px;margin:8px 0">${T.ready}</div><div style="display:flex;gap:7px;align-items:center"><span>${T.next}</span><input id="${P}-int" type="number" min="${C.min}" max="${C.max}" style="width:75px"><span>${T.sec}</span></div><div style="display:flex;gap:7px;margin:8px 0"><button id="${P}-start" style="flex:1">${T.start}</button><button id="${P}-pause">${T.pause}</button></div><button id="${P}-once">${T.once}</button> <button id="${P}-manage">${T.manage}</button><div style="margin-top:7px"><button id="${P}-scan">${T.scanbtn}</button> <button id="${P}-local">${T.local}</button></div>`;document.body.appendChild(e);document.getElementById(P+'-start').onclick=start;document.getElementById(P+'-pause').onclick=pause;document.getElementById(P+'-once').onclick=()=>batch(false);document.getElementById(P+'-manage').onclick=manager;document.getElementById(P+'-scan').onclick=async()=>{if(busy)return;busy=true;try{let m=await scan(status);status(T.scanbtn+': '+m.size)}finally{busy=false;draw()}};document.getElementById(P+'-local').onclick=()=>status(`OK: ${success().length} · Failed: ${(gs('bad',[])||[]).length} · ${T.active}: ${active().length}`);let i=document.getElementById(P+'-int');i.value=geti();i.onchange=()=>{i.value=seti(i.value)};draw()}
function istarget(){return /\/settings\/(?:muted_keywords|add_muted_keyword)/.test(location.pathname)}
function mount(){if(!document.body)return;if(istarget())panel();else document.getElementById(P+'-panel')?.remove()}
mount();setInterval(mount,1000);setInterval(()=>{if(istarget())draw()},1000);window.FSX={version:V,active,scan,start,pause,manager,panel,setIntervalSeconds:seti,builtin:()=>[...W]};if(istarget()&&gs('auto',false))setTimeout(start,1800);
})();